---
title: "MATH 216 Homework 2 Shiny App"
author: "WRITE YOUR NAME HERE"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}
inputPanel(
  
  # Input name
  textInput("name", label = "Enter Name:", value="Jane"),
  # Input start year
  numericInput("start_year", label = "Start Year:", value = 1880, min = 1880, max = 2014, step = 1),
  # Input end year
  numericInput("end_year", label = "End Year:", value = 2014, min = 1880, max = 2014, step = 1)
  
)

renderPlot({
  
  # Pretend Inputs
  input_name <- "Albert"
  input_start_year <- 1880
  input_end_year <- 2014
  
  # Generate Plots
  names <- babynames %>%
    filter(name == input$name & year >= input$start_year & year <= input$end_year )
  ggplot(data=names, aes(x=year, y=prop, col=sex)) + 
    geom_line()
  
})
```
